spring.application.name=gateway

# -------- ROUTE 1 --------
spring.cloud.gateway.routes[0].id=aluno-service
spring.cloud.gateway.routes[0].uri=http://aluno-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/alunos/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# -------- ROUTE 2 --------
spring.cloud.gateway.routes[1].id=viagem-service
spring.cloud.gateway.routes[1].uri=http://viagem-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/viagens/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# -------- JWT --------
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/busco

management.endpoints.web.exposure.include=health,prometheus,metrics
management.endpoint.health.probes.enabled=true


server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
